### ISSUE TITLE
Create Typeform

### ISSUE THREAD

**Issue by richard4s** [richard4s/Digilabs#1]
1. Create a registration typeform
2. A contact Us typeform

**Comment by AbdulsalamDahood** [comment]
Why should I create typeform, baba do your job finish

**Comment by richard4s** [comment]
Yepa!💔💔😩😩😩

**Comment by richard4s** [comment]
Created the typeform with the link:  https://afolabi6.typeform.com/to/DmZT80

**Comment by AbdulsalamDahood** [comment]
The URL, can you edit it instead of Afolabi6 make it digilabs.

Or just chang your username to digilabs

**Comment by richard4s** [comment]
That means I'll have to create the digilabs email first

**Comment by AbdulsalamDahood** [comment]
Nha, just go to your account you will see typeform url just edit

**Comment by richard4s** [comment]
You can't edit the link. It's your `(name + the number of forms you've created).typeform/com/to/md5hash`

**Comment by AbdulsalamDahood** [comment]
You can just go your account page and edit typeform url, I know what am saying

**Comment by richard4s** [comment]
Ok sir, wanna help out? 😏

**Comment by richard4s** [comment]
We have changed the link with a pizza bet that we both lost🤣🤣🤣

**Comment by AbdulsalamDahood** [comment]
> We have changed the link with a pizza bet that we both lost

guy, i won the bet link is changeable
